
Sidebar.prototype.addRTLPalette = function () {
    this.addPaletteFunctions('rtl', 'RTL', true, [
        this.createVertexTemplateEntry('ellipse;whiteSpace=wrap;html=1;aspect=fixed;fillColor=#000000;strokeColor=none;noLabel=1;snapToPoint=1;perimeter=none;resizable=0;rotatable=0;', 5, 5, '', 'Junction point', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'junction', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=mux;drawPins=0;left=4;right=1;bottom=0;', 30, 100, '', 'Mux', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'mux ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=mux;drawPins=1;left=4;right=1;bottom=0;', 40, 100, '', 'Mux', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'mux ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=demux;drawPins=0;left=1;right=4;bottom=0;', 30, 100, '', 'DeMux', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'demux ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=demux;drawPins=1;left=1;right=4;bottom=0;', 40, 100, '', 'DeMux', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'demux ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=crossbar;drawPins=0;left=4;right=4;bottom=0;', 60, 100, '', 'Crossbar', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'crossbar ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=crossbar;drawPins=1;left=4;right=4;bottom=0;', 60, 100, '', 'Crossbar', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'crossbar ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=combinational;drawPins=0;left=3;right=2;bottom=0;top=0;', 80, 120, '', 'Combinational Logic', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'combinational ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=combinational;drawPins=1;left=3;right=2;bottom=0;top=0;', 80, 120, '', 'Combinational Logic', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'combinational ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=sequential;drawPins=0;left=3;right=2;bottom=0;top=0;', 80, 120, 'Entity', 'Entity', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;kind=sequential;drawPins=1;left=3;right=2;bottom=0;top=0;', 80, 120, 'Entity', 'Entity', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'entity', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;left=,:clk;right=,:np;top=0;bottom=0;drawPins=0;snapToPoint=1;resizable=0;editable=1;', 40, 60, '', 'Register', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'reg', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;verticalAlign=top;spacing=0;spacingTop=7;left=1;right=:n;top=0;bottom=0;drawPins=1;snapToPoint=1;resizable=0;editable=0;', 60, 60, '1', 'NOT', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'not', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;verticalAlign=top;spacing=0;spacingTop=7;left=2;right=1;top=0;bottom=0;drawPins=1;snapToPoint=1;resizable=0;editable=0;', 60, 60, '&', 'AND', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'and', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;verticalAlign=top;spacing=0;spacingTop=7;left=2;right=:n;top=0;bottom=0;drawPins=1;snapToPoint=1;resizable=0;editable=0;', 60, 60, '&', 'NAND', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'nand', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;verticalAlign=top;spacing=0;spacingTop=7;left=2;right=1;top=0;bottom=0;drawPins=1;snapToPoint=1;resizable=0;editable=0;', 60, 60, '≥1', 'OR', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'or', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;verticalAlign=top;spacing=0;spacingTop=7;left=2;right=:n;top=0;bottom=0;drawPins=1;snapToPoint=1;resizable=0;editable=0;', 60, 60, '≥1', 'NOR', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'nor', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;verticalAlign=top;spacing=0;spacingTop=7;left=2;right=1;top=0;bottom=0;drawPins=1;snapToPoint=1;resizable=0;editable=0;', 60, 60, '=1', 'XOR', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'xor', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;verticalAlign=top;spacing=0;spacingTop=7;left=2;right=:n;top=0;bottom=0;drawPins=1;snapToPoint=1;resizable=0;editable=0;', 60, 60, '=1', 'XNOR', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'xnor', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=2;shape=mxgraph.rtl.abstract.bus;labelPosition=center;verticalLabelPosition=top;verticalAlign=bottom;', 10, 80, 'Bus', 'Bus', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'bus', 'rtl ').join(' ')),
        this.createVertexTemplateEntry('shadow=0;dashed=0;align=center;html=1;strokeWidth=1;shape=mxgraph.rtl.abstract.entity;container=1;collapsible=0;drawPins=1;leftArr=no style,input:i,input:in,clock:c,clock:clk,clock:clock,negated clock:nclk,negated clock:nclock,not connected:nc;rightArr=output:o,output:out,input/output:io,input/output:inout,multiple types:nc:n:clk;left=9;right=5;topArr=1,2,3,4;top=you,may,set,multiple,pins,at,once;bottom=6;bottomArr=no pin:no,no pin:np,no pin:nopin,negated:n,negated:neg,negated:not;', 400, 540, '<h1>PIN TYPES</h1><br>can be specified via format string<br>"NAME:TYPE"<br>in the properties.<br>(multiple types can be set)<br><br>You may specify multiple pins at once<br>(separated by comma)<br>or set a number of pins<br>and specify each pin on its own.', 'Pin Types Legend', null, null, this.getTagsForStencil('mxgraph.rtl.abstract', 'pin', 'types', 'rtl ').join(' ')),
    ]);
}